# src/configs/sft_6_multitask_joint_no_adapter.yaml
model_name_or_path: "/content/drive/MyDrive/ANLP_models/mlm_biomed"
#put correct path to the biomed mlm model above

train_files:
  - "data/processed/biomed_sentiment_train.jsonl"
  - "data/processed/finance_sentiment_train.jsonl"

eval_files:
  - "data/processed/biomed_sentiment_val.jsonl"
  - "data/processed/finance_sentiment_val.jsonl"

output_dir: "outputs/sft_6_multitask_joint_no_adapter"

num_labels: 3
batch_size: 8
learning_rate: 5e-5
epochs: 3
label_map: "data/processed/label_map.json"

use_lora: false
