
model_name_or_path: "bhadresh-savani/bert-base-go-emotion"

train_files:
  - "data/processed/finance_sentiment_train.jsonl"
  - "data/processed/biomed_sentiment_train.jsonl"

eval_files:
  - "data/processed/finance_sentiment_val.jsonl"
  - "data/processed/biomed_sentiment_val.jsonl"

output_dir: "outputs/sft_1_baseline_goemotion"

num_labels: 3
batch_size: 8
learning_rate: 5e-5
epochs: 3
label_map: "data/processed/label_map.json"

use_lora: false   # full fine-tune
