# src/configs/sft_2_biomed_mlm_no_adapter.yaml
model_name_or_path: "outputs/mlm_biomed"

train_files:
  - "data/processed/biomed_sentiment_train.jsonl"
eval_files:
  - "data/processed/biomed_sentiment_val.jsonl"

output_dir: "outputs/sft_2_biomed_mlm_no_adapter"

num_labels: 3
batch_size: 8
learning_rate: 5e-5
epochs: 3
label_map: "data/processed/label_map.json"

use_lora: false
